bootstrap_errors_list:  
programs with errors: []

rename_me_errors_list:  
test lnp_magic.py: -F option doesn't work.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 925, in complete_lnp_magic_test
    raise NameError("-F option doesn't work")

test plot_magic_keys.py: raw_input at the end.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1190, in complete_plot_magic_keys_test
    raise NameError('raw_input at the end')

test HUJI_magic.py: initializing variables were removed.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1278, in complete_HUJI_magic_test
    raise NameError('initializing variables were removed')

test curie.py: curie.py still has a lone raw_input() at its end....  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1182, in complete_curie_test
    raise NameError('curie.py still has a lone raw_input() at its end...')

programs with errors: ['test lnp_magic.py', 'test plot_magic_keys.py', 'test HUJI_magic.py', 'test curie.py']

random_errors_list:  
programs with errors: []

extra_output_errors_list.:  
test IODP_csv.py: Wrong output -- output list did not match correct_output_list -- running IODP_csv_magic.py.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Extra_output.py", line 439, in complete_IODP_csv_magic_test
    IODP_csv.check_file_output(out3, ref3, "correct")
  File "Extra_output.py", line 135, in check_file_output
    self.check_list_output(out, ref)
  File "Extra_output.py", line 93, in check_list_output
    raise NameError("Wrong output -- output list did not match correct_output_list -- running " + str(self.name))

programs with errors: ['test IODP_csv.py']

