bootstrap_errors_list:  
test watsonsV.py: [Errno 2] No such file or directory.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Bootstrap.py", line 130, in complete_watsonsV_test
    output1 = do_watsonsV()
  File "Bootstrap.py", line 118, in do_watsonsV
    obj = env.run("watsonsV.py", "-f", watsonsV_infile, "-f2", watsonsV_infile2, stdin='q')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 237, in run
    env=clean_environ(self.environ))
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception

test eqarea_magic.py: [Errno 2] No such file or directory.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Bootstrap.py", line 185, in complete_eqarea_magic_test
    obj = env.run('eqarea_magic.py', '-WD', directory, '-f', eqarea_magic_infile, '-obj', 'loc', '-crd', 'g', '-ell', 'Be', stdin='q')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 237, in run
    env=clean_environ(self.environ))
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception

test scalc_magic.py: [Errno 2] No such file or directory.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Bootstrap.py", line 89, in complete_scalc_magic_test
    output = do_scalc_magic()
  File "Bootstrap.py", line 79, in do_scalc_magic
    obj = env.run('scalc_magic.py', '-f', file_prefix + 'scalc_magic_example.txt', '-v', '-b')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 237, in run
    env=clean_environ(self.environ))
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception

test find_EI.py: [Errno 2] No such file or directory.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Bootstrap.py", line 153, in complete_find_EI_test
    output1 = run_EI(1000)
  File "Bootstrap.py", line 140, in run_EI
    obj = env.run('find_EI.py', '-f', file_prefix + 'find_EI_example.dat', '-nb', num, stdin='a')
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/site-packages/ScriptTest-1.2-py2.7.egg/scripttest/__init__.py", line 237, in run
    env=clean_environ(self.environ))
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/Library/Frameworks/Python.framework/Versions/7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception

programs with errors: ['test watsonsV.py', 'test eqarea_magic.py', 'test scalc_magic.py', 'test find_EI.py']

